#! /bin/sh

sxhkd &
${HOME}/.config/polybar/launch.sh
xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         2
bspc config window_gap          12
bspc config bottom_padding	25	
bspc config top_padding 	0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Yad state=floating
bspc rule -a Firefox desktop='^4'
